Repository AndyOooh/ETHDenver-group14, pull requests merged in 2022-11, with the labels that each got.

#2 Test: Assert owner of deployed HelloWorld.sol
  test/HelloWorld.ts
Labels: test

#3 Feature: Add template for pull request summaries
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#5 ballot contract and deploy script
  .env.example
  .gitignore
  contracts/Ballot.sol
  hardhat.config.ts
  package.json
  scripts/deploy-ballot.ts
  scripts/deploy-helloWorld.ts
  scripts/deploy.ts
  test/Ballot.ts
  tsconfig.json
Labels: enhancement
